server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index home-v2.html;

    location = / {
        try_files /home-v2.html =404;
    }

    location = /coming-soon {
        try_files /coming-soon.html =404;
    }

    location = /home {
        try_files /home.html =404;
    }

    location = /v2 {
        try_files /home-v2.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
